### ISSUE TITLE
undefined method `append_path' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by mixelpixel** [emberjs/ember-rails#531]
`rails s` invokes this error msg upon exiting:
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/ember-rails-0.14.1/lib/ember_rails.rb:33:in \`block in <class:Railtie>': undefined method `append_path' for nil:NilClass (NoMethodError)

ember_rails.rb
```
rb:29         tmp_path = app.root.join("tmp/ember-rails")
...
rb:33         app.assets.append_path(tmp_path)
```

I'm working on win7 (Rails 4.2.5.1 came with Ruby 2.2 from http://railsinstaller.org/en) so I thought maybe this might be related to directory path syntax? If it would be useful I can post the entire `from...` sequence. Otherwise I am unfamiliar with the `.append_path` method but it appears to be inherited from Sprockets: http://www.rubydoc.info/github/rails/sprockets/Sprockets%2FPaths%3Aappend_path but sprockets is not required in ember_rails.rb. I'll try requiring it but I thought this might be a place to ask for help, thanks!

**Comment by tricknotes** [comment]
Can use try using the latest release ([0.20.5](https://rubygems.org/gems/ember-rails/versions/0.20.5)) of ember-rails?

It seems your ember-rails is too old.
